### ISSUE TITLE
Review of Menu Category List && Featured

### ISSUE THREAD

**Issue by jesstice** [redacademy/moustache-summer-2017#101]
- [x] Review prop types
- [x] Review indentation (4 spaces)
- [x] Review font, font size, font colour
- [x] Check for semi-colons
- [x] Check for extra spaces... and remove them!
- [x] Check the problems tab
- [x] Check against original design

**Comment by kmsolberg** [comment]
- [ ] Check layout of item title on more than one line, ex. Juices category
