### ISSUE TITLE
Review of Events scene

### ISSUE THREAD

**Issue by jesstice** [redacademy/moustache-summer-2017#97]
- [x] Review Events list
- [x] Review single events
- [x] Review prop types
- [x] Review indentation (4 spaces)
- [x] Review font, font size, font colour
- [x] Check for semi-colons
- [x] Check for extra spaces... and remove them!
- [x] Check the problems tab
- [x] Check against original design

**Comment by kmsolberg** [comment]
- [ ] change header selected index on single event to 0
